/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jv4l2_Jv4l2JNI */

#ifndef _Included_org_jv4l2_Jv4l2JNI
#define _Included_org_jv4l2_Jv4l2JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jv4l2_Jv4l2JNI
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jv4l2_Jv4l2JNI_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jv4l2_Jv4l2JNI
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jv4l2_Jv4l2JNI_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jv4l2_Jv4l2JNI
 * Method:    setProperty
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_jv4l2_Jv4l2JNI_setProperty
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
