IF (LIBV4L2_INCLUDE_DIR AND LIBV4L2_LIBRARY)
    SET (LIBV4L2_FIND_QUIETLY TRUE)
ENDIF (LIBV4L2_INCLUDE_DIR AND LIBV4L2_LIBRARY)

FIND_PATH (LIBV4L2_INCLUDE_DIR libv4l2.h)

FIND_LIBRARY (LIBV4L2_LIBRARY v4l2)

INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (LibV4L2 DEFAULT_MSG LIBV4L2_INCLUDE_DIR LIBV4L2_LIBRARY)

MARK_AS_ADVANCED(LIBV4L2_INCLUDE_DIR LIBV4L2_LIBRARY)

include_directories(${LIBV4L2_INCLUDE_DIR})